"""Small, RWKV-oriented answer adapters used before LightEval scoring.

The model is prompted in the RWKV chat format, while a number of LightEval
metrics expect the answer to already be in their canonical form.  Keep that
boundary explicit: raw completions remain untouched in ``ModelResponse.text``
and this module only produces ``text_post_processed`` for scoring.
"""

from __future__ import annotations

import re
from typing import Iterable

try:
    # This is the checked-in LightEval source used by the project, not an
    # external runtime dependency. Reuse its established LaTeX equivalence
    # rules after extracting the final answer.
    from lighteval.metrics.normalizations import math_normalizer as _official_math_normalizer
except ImportError:  # pragma: no cover - standalone adapter tests
    _official_math_normalizer = None


_USER_TURN = "\nUser:"
_EOD = "\x00"
_CODE_FORMATS = {
    "code",
    "code_completion",
    "diff_patch",
    "generic_code",
    "python_function",
    "python_program",
    "python_snippet",
}
_CHOICE_FORMATS = {"choice", "multiple_choice", "multichoice", "mmlu", "math_choice"}
_MATH_FORMATS = {"math", "math_boxed", "math_free_response", "math_open_qa"}
_MATH_CUE = re.compile(
    r"(?:final\s+answer|answer\s+is|the\s+answer(?:\s+is)?|therefore|answer|"
    r"最终答案|答案|结论)"
    r"\s*(?:[,：:]\s*)?(?:the\s+answer\s*(?:is|[:：])\s*)?"
    r"(?P<value>[^\n\r]*)",
    re.IGNORECASE,
)


def truncate_rwkv_completion(text: str, stops: Iterable[str] = ()) -> str:
    """Apply the text-level RWKV turn/EOD guards.

    The endpoint already applies its JSON ``stop`` list.  Repeating the
    guards here is intentional: score-only runs reconstruct responses from
    the database and must use the same boundary even when an old row was
    generated by a different endpoint implementation.
    """

    value = str(text or "")
    positions = [position for position in (value.find(_USER_TURN), value.find(_EOD)) if position >= 0]
    for stop in stops:
        marker = str(stop or "")
        if marker and marker not in {_USER_TURN, _EOD}:
            position = value.find(marker)
            if position >= 0:
                positions.append(position)
    return value[: min(positions)] if positions else value


def answer_region(text: str) -> str:
    """Remove a completed think block without guessing inside an open one."""

    value = str(text or "")
    closing = value.lower().rfind("</think>")
    if closing >= 0:
        return value[closing + len("</think>") :].lstrip()
    return value.strip()


def _choice_letters(prompt: str) -> set[str]:
    value = str(prompt or "")
    # Statements such as ``I.``/``II.`` often appear at the beginning of a
    # multiple-choice question. Parse labels only from the answer choices
    # section so those Roman-numeral statements cannot reject A/B/C/D.
    marker = re.search(r"answer\s+choices?\s*[:：]", value, re.IGNORECASE)
    choices_text = value[marker.end() :] if marker else value
    matches = re.findall(
        r"(?:\(([A-Z])\)|\[([A-Z])\]|^\s*([A-Z])\s*[.):：])",
        choices_text,
        re.IGNORECASE | re.MULTILINE,
    )
    labels = {
        group.upper()
        for match in matches
        for group in match
        if group
    }
    # The prompt is not available in the database-side symmetric comparator.
    # The curated choice tasks use four or five options, so retain E when no
    # prompt is available instead of silently rejecting a valid fifth choice.
    return labels or set("ABCDE")


def extract_choice_answer(text: str, *, prompt: str = "") -> str:
    """Extract one final option and return the official ``" A"`` form.

    The order mirrors the RWKV knowledge evaluator: a direct standalone
    letter wins, then an explicit answer cue, then a final option-shaped line.
    We deliberately do not scan arbitrary capital letters from the reasoning.
    """

    value = answer_region(text)
    valid = _choice_letters(prompt)
    direct = re.fullmatch(r"\s*[\[\(]?([A-Z])[\]\)]?\s*[.!]?\s*", value, re.IGNORECASE)
    if direct and direct.group(1).upper() in valid:
        return f" {direct.group(1).upper()}"

    # Match the same first explicit cue as the local LightEval
    # ``GenerativeChoice`` scorer.  In particular, do not reverse-scan the
    # reasoning: ``Answer Choices: (A) ...`` is an option-list header, while
    # ``Answer Choice: (D)`` and ``option (D)`` are selected answers.
    official_cue = re.compile(
        r"(?is)(?:answer|option|choice)(?:\s+is)?\s*[:：]?\s*[\(\[]?([A-Z])\b"
    )
    match = official_cue.search(value)
    if match is not None:
        letter = match.group(1).upper()
        if letter in valid:
            return f" {letter}"

    cues = re.compile(
        r"(?:final\s+answer|correct\s+answer|answer|答案|正确选项|选项)"
        r"\s*(?:is|为|是)?\s*[:：]?\s*[\[\(]?([A-Z])[\]\)]?\b",
        re.IGNORECASE,
    )
    for match in cues.finditer(value):
        letter = match.group(1).upper()
        if letter in valid:
            return f" {letter}"

    line_pattern = re.compile(r"^\s*[\[\(]?([A-Z])[\]\)]?\s*[.):：-](?:\s|$)", re.IGNORECASE)
    for line in value.splitlines():
        match = line_pattern.match(line)
        if match and match.group(1).upper() in valid:
            return f" {match.group(1).upper()}"
    # Do not guess from the final reasoning line. A choice task has no usable
    # answer unless a direct letter, explicit cue, or option-shaped line was
    # found; returning prose here makes eval.answer look like a choice while
    # silently storing an arbitrary piece of reasoning.
    return ""


_CHOICE_LABEL_PATTERN = re.compile(
    r"(?m)^\s*(?:\(([A-Z])\)|\[([A-Z])\]|([A-Z])\s*[.):\-\uFF1A])\s*",
    re.IGNORECASE,
)


def _choice_label(match: re.Match[str]) -> str:
    for group in match.groups():
        if group:
            return group.upper()
    return ""


def _choice_letters_v2(prompt: str) -> set[str]:
    value = str(prompt or "")
    marker = re.search(r"(?:answer\s+choices?|options?)\s*[:\uFF1A]", value, re.IGNORECASE)
    choices_text = value[marker.end() :] if marker else value
    matches = list(_CHOICE_LABEL_PATTERN.finditer(choices_text))
    candidates: list[tuple[int, int, set[str]]] = []
    for index, match in enumerate(matches):
        if _choice_label(match) != "A":
            continue
        labels = {"A"}
        cursor = index
        while cursor + 1 < len(matches) and len(labels) < 26:
            expected = chr(ord(max(labels)) + 1)
            next_index = next(
                (
                    candidate_index
                    for candidate_index in range(cursor + 1, len(matches))
                    if _choice_label(matches[candidate_index]) == expected
                ),
                None,
            )
            if next_index is None:
                break
            labels.add(expected)
            cursor = next_index
        if len(labels) >= 2:
            candidates.append((len(labels), matches[cursor].end(), labels))
    return (
        max(candidates, key=lambda item: (item[0], item[1]))[2]
        if candidates
        else set("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    )


def extract_choice_answer_v2(text: str, *, prompt: str = "") -> str:
    """Extract the last valid RWKV choice token from a response."""

    value = truncate_rwkv_completion(text, ())
    valid = _choice_letters_v2(prompt)
    candidates: list[tuple[int, str]] = []
    prompt_header = re.compile(r"\b(?:answer\s+choices|options?|choices)\s*:", re.IGNORECASE)

    def add(match: re.Match[str]) -> None:
        letter = match.group(1).upper()
        if letter not in valid:
            return
        line_start = value.rfind("\n", 0, match.start()) + 1
        line_end = value.find("\n", match.end())
        if line_end < 0:
            line_end = len(value)
        line = value[line_start:line_end]
        if prompt_header.search(line[: match.start() - line_start]):
            return
        candidates.append((match.start(), letter))

    patterns = (
        r"\\(?:boxed|fbox)\s*\{\s*(?:(?:option|choice)\s+)?"
        r"([A-Z])(?![A-Za-z_])(?=\s*(?:\}|[.):\-]))",
        r"<(?:answer|final_answer)>\s*[\(\[]?\s*([A-Z])"
        r"(?![A-Za-z_])\s*[\)\]]?\s*</(?:answer|final_answer)>",
        r"(?<![A-Za-z_])\$\s*([A-Z])(?![A-Za-z_])\s*\$",
        r"(?<![A-Za-z_])(?:\*\*|__)\s*([A-Z])(?![A-Za-z_])\s*(?:\*\*|__)",
        r"(?:\b(?:answer|option|choice|letter|statement|result|value)\b|"
        r"答案|正确选项|选项)\s*(?:(?:is|was|equals|为|是)\s*)?"
        r"(?:(?:option|choice)\s*)?[:=：]?\s*"
        r"(?:\*\*|__|\$|[\(\[])?\s*([A-Z])(?![A-Za-z_])",
    )
    for pattern in patterns:
        for match in re.finditer(pattern, value, re.IGNORECASE):
            add(match)

    for match in re.finditer(
        r"(?m)^[ \t]*(?:[\(\[]\s*)?([A-Z])(?![A-Za-z_])"
        r"(?:\s*[\)\]])?[ \t]*[.!]?[ \t]*$",
        value,
        re.IGNORECASE,
    ):
        add(match)

    return f" {candidates[-1][1]}" if candidates else ""


def _boxed_candidates(text: str) -> list[str]:
    """Return complete boxed values in source order.

    A completion can be cut off after a later ``\\boxed{``. We must not let
    that incomplete tail hide the last complete answer that came before it.
    Keeping all complete candidates also lets the math validator skip a
    syntactically complete box whose contents contain a truncated ``\\frac``.
    """

    candidates: list[str] = []
    matches = list(re.finditer(r"\\(?:boxed|fbox)\s*\{", text, re.IGNORECASE))
    for match in matches:
        start = match.end()
        depth = 1
        for index in range(start, len(text)):
            if text[index] == "{" and (index == 0 or text[index - 1] != "\\"):
                depth += 1
            elif text[index] == "}" and (index == 0 or text[index - 1] != "\\"):
                depth -= 1
                if depth == 0:
                    candidates.append(text[start:index].strip())
                    break
    return candidates


def _last_boxed(text: str) -> str | None:
    candidates = _boxed_candidates(text)
    return candidates[-1] if candidates else None


def _read_math_argument(text: str, start: int) -> tuple[str | None, int]:
    """Read one fraction argument and return ``(value, next_index)``."""

    index = start
    while index < len(text) and text[index].isspace():
        index += 1
    if index >= len(text):
        return None, index

    if text[index] != "{":
        # LightEval accepts the compact form ``\\frac12``. It treats the
        # next two tokens as the numerator and denominator.
        return text[index], index + 1

    begin = index + 1
    depth = 1
    index += 1
    while index < len(text):
        if text[index] == "{" and (index == 0 or text[index - 1] != "\\"):
            depth += 1
        elif text[index] == "}" and (index == 0 or text[index - 1] != "\\"):
            depth -= 1
            if depth == 0:
                value = text[begin:index]
                return (value if value.strip() else None), index + 1
        index += 1
    return None, index


def _has_complete_fractions(text: str) -> bool:
    """Reject truncated fraction commands before calling LightEval.

    The upstream normalizer indexes the suffix after ``\\frac``. A cut-off
    completion such as ``\\frac`` or ``\\frac{1}`` therefore raises instead
    of producing an answer. This check requires two non-empty arguments for
    every fraction command.
    """

    for match in re.finditer(r"\\(?:dfrac|tfrac|frac)\b", text):
        numerator, next_index = _read_math_argument(text, match.end())
        if numerator is None:
            return False
        denominator, _ = _read_math_argument(text, next_index)
        if denominator is None:
            return False
    return True


def _is_complete_math_value(value: str) -> bool:
    if not value.strip() or not _has_complete_fractions(value):
        return False
    depth = 0
    for index, char in enumerate(value):
        if char == "{" and (index == 0 or value[index - 1] != "\\"):
            depth += 1
        elif char == "}" and (index == 0 or value[index - 1] != "\\"):
            depth -= 1
            if depth < 0:
                return False
    return depth == 0


def _looks_like_math_value(value: str) -> bool:
    """Reject prose that happens to follow an answer cue."""

    value = str(value or "").strip()
    if not value or re.search(r"[^0-9A-Za-z\\{}()[\]^_+\-*/=.,%<>|! ]", value):
        return False
    if not re.search(r"\d|\\[A-Za-z]+|[=^_]", value):
        return False
    # Remove LaTeX command names before inspecting bare words. This permits
    # ``P(\\omega)=...`` but rejects prose such as ``Theproduct`` even when
    # the same line also contains a LaTeX command.
    residual = re.sub(r"\\[A-Za-z]+", " ", value)
    residual = re.sub(r"[0-9{}()[\]^_+\-*/=.,%<>|!\s]+", " ", residual)
    words = re.findall(r"[A-Za-z]+", residual)
    if any(len(word) > 2 for word in words):
        return False
    return True


def _canonical_integer(value: str) -> str:
    """Canonicalize integer spelling, including AIME's leading zeros."""

    match = re.fullmatch(r"([+-]?)(\d+)", value)
    if not match:
        return value
    sign, digits = match.groups()
    canonical = str(int(digits))
    return f"-{canonical}" if sign == "-" and canonical != "0" else canonical


def _cued_math_value(value: str) -> str:
    """Extract a short math expression from one answer-cue match."""

    candidate = str(value or "").strip().strip("` ")
    candidate = re.sub(
        r"^(?:[,;:：=]|is\b|the\s+answer\s*(?:is|[:：]))\s*",
        "",
        candidate,
        flags=re.IGNORECASE,
    )
    delimited = list(
        re.finditer(
            r"\\\(([^\n\r]*?)\\\)|\\\[([^\n\r]*?)\\\]|\$([^\n\r]+?)\$",
            candidate,
        )
    )
    if delimited:
        match = delimited[-1]
        candidate = next(group for group in match.groups() if group is not None).strip()

    integer_or_decimal = re.match(r"[+-]?\d[\d,]*(?:\.\d+)?", candidate)
    if integer_or_decimal:
        return integer_or_decimal.group(0)
    fraction = re.match(r"\\(?:frac|dfrac|tfrac)\b", candidate)
    if fraction:
        _, next_index = _read_math_argument(candidate, fraction.end())
        _, end_index = _read_math_argument(candidate, next_index)
        if end_index > next_index:
            return candidate[:end_index]
    return candidate.rstrip(".;,。；，")


def _last_delimited_math_value(text: str) -> str | None:
    """Extract the value from the final complete inline/display math block.

    Reasoning-prefilled completions often repeat the result after ``</think>``
    without writing ``Final answer:`` or ``\\boxed{...}``, for example
    ``The maximum is \\(\\sqrt{...}=540\\).`` The final equality's right
    hand side is the answer, while earlier equations in the explanation must
    not be considered. This helper is only used on the post-think answer
    region, so it does not turn arbitrary reasoning numbers into answers.
    """

    blocks = list(
        re.finditer(
            r"\\\(([^\n\r]*?)\\\)|\\\[([^\n\r]*?)\\\]|\$([^\n\r]+?)\$",
            text,
        )
    )
    if not blocks:
        return None
    candidate = next(group for group in blocks[-1].groups() if group is not None).strip()
    # A final explanatory display frequently contains ``expression = answer``.
    # Split only on an unescaped equality sign; LaTeX relations such as
    # ``\\le`` and ``\\neq`` must remain untouched.
    equalities = list(re.finditer(r"(?<!\\)=(?!=)", candidate))
    if equalities:
        candidate = candidate[equalities[-1].end() :].strip()
    return candidate or None


def _normalize_math_value(value: str) -> str:
    """Return one delimiter-free value for both prediction and gold text."""

    normalized = str(value or "").strip().strip("` ")
    wrappers = (("\\(", "\\)"), ("\\[", "\\]"))
    changed = True
    while changed and normalized:
        changed = False
        for left, right in wrappers:
            if normalized.startswith(left) and normalized.endswith(right):
                normalized = normalized[len(left) : -len(right)].strip()
                changed = True
        if len(normalized) >= 2 and normalized[0] == normalized[-1] == "$":
            normalized = normalized[1:-1].strip()
            changed = True
    normalized = normalized.replace("\\left", "").replace("\\right", "")
    normalized = normalized.replace("\\!", "")
    normalized = normalized.replace("\\dfrac", "\\frac").replace("\\tfrac", "\\frac")
    normalized = re.sub(r"\s+", "", normalized)
    return normalized.rstrip(".。")


def _format_math_value(value: str) -> str:
    normalized = _normalize_math_value(value)
    if not _looks_like_math_value(normalized) or not _is_complete_math_value(normalized):
        return ""
    normalized = _canonical_integer(normalized)
    if normalized and _official_math_normalizer is not None:
        # LightEval's normalizer expects a complete solution containing a
        # boxed answer. Re-wrap our already extracted value to reuse its
        # fraction/spacing equivalence rules.
        try:
            normalized = _official_math_normalizer(f"\\boxed{{{normalized}}}") or normalized
        except Exception:
            # A malformed candidate is not an answer. The caller will try the
            # previous complete candidate, if one exists.
            return ""
        if not _is_complete_math_value(normalized):
            return ""
    return f"${normalized}$" if normalized else ""


def normalize_math_answer(value: str) -> str:
    """Canonicalize one mathematical answer, whether it is gold or model text.

    This is deliberately separate from extraction: callers can pass either a
    raw completion or a dataset answer through the same function. In
    particular ``$4000$``, ``\\boxed{4000}``, and ``4000`` all become the same
    LaTeX value.
    """

    raw = str(value or "")
    boxed_candidates = _boxed_candidates(raw)
    if boxed_candidates:
        for boxed in reversed(boxed_candidates):
            formatted = _format_math_value(boxed)
            if formatted:
                return formatted
        return ""
    formatted = _format_math_value(raw)
    if formatted:
        return formatted
    for match in reversed(list(_MATH_CUE.finditer(raw))):
        formatted = _format_math_value(_cued_math_value(match.group("value")))
        if formatted:
            return formatted
    return ""


def extract_math_answer(text: str) -> str:
    """Extract one canonical mathematical value from either side of a match.

    Gold rows and model continuations are deliberately sent through this same
    function. The scorer should compare ``36`` with ``36`` rather than rely on
    whether one side happened to contain ``$`` or ``\\boxed{...}``.
    """

    raw_value = str(text or "")
    # Math answers may be emitted inside the think block.  Search the complete
    # response first and choose the last *complete* boxed expression; the
    # parser skips a later, truncated ``\boxed{`` and can still use an earlier
    # complete answer.
    boxed_candidates = _boxed_candidates(raw_value)
    if boxed_candidates:
        for boxed in reversed(boxed_candidates):
            formatted = _format_math_value(boxed)
            if formatted:
                return formatted
        return ""

    if re.search(r"\\(?:boxed|fbox)\s*\{", raw_value, re.IGNORECASE):
        return ""

    value = answer_region(raw_value)

    matches = list(_MATH_CUE.finditer(value))
    if matches:
        for match in reversed(matches):
            candidate = _format_math_value(_cued_math_value(match.group("value")))
            if candidate:
                return candidate
        return ""

    # A closed reasoning prefill may repeat the final result as prose without
    # an explicit answer cue. Use only the final complete math block in the
    # answer region and, for ``expression = result``, its right-hand side.
    if "</think>" in raw_value.lower():
        candidate = _last_delimited_math_value(value)
        if candidate:
            formatted = _format_math_value(candidate)
            if formatted:
                return formatted

    # Without a cue, accept only a standalone short answer. Never scan the
    # last reasoning line: a long equation at the token limit is not an
    # answer and must remain empty.
    if "\n" not in value:
        candidate = _format_math_value(value)
        if candidate:
            return candidate
    return ""


def answers_match(
    model_answer: str,
    reference_answer: str,
    *,
    domain: str | None,
    request_format: str | None,
) -> bool | None:
    """Compare two answers with the same domain-specific normalization.

    ``None`` means the domain has a richer native scorer and should not be
    reduced to string equality in the per-completion diagnostic table.
    """

    domain_name = str(domain or "").strip().lower()
    format_name = str(request_format or "").strip().lower()
    if format_name in _CHOICE_FORMATS:
        left = extract_choice_answer_v2(model_answer)
        right = extract_choice_answer_v2(reference_answer)
        return bool(left and right and left == right)
    # Some AGIEval tasks belong to the math domain but are multiple-choice
    # tasks (for example aqua-rat).  The explicit transport format is more
    # specific than the broad domain and must win here, just as it does in
    # adapt_answer().
    if domain_name == "math" or format_name in _MATH_FORMATS:
        # Use the same extractor on both sides. It handles ordinary LaTeX
        # wrappers as well as a model's closed ``</think>`` answer region.
        left = extract_math_answer(model_answer)
        right = extract_math_answer(reference_answer)
        return bool(left and right and left == right)
    if domain_name == "coding" or format_name in _CODE_FORMATS:
        # Code tasks have a native execution scorer. Their reference answer
        # is commonly an empty transport value because the tests live in
        # ``Doc.specific``; string equality would incorrectly turn every
        # native pass into a database failure.
        return None
    return None


def extract_code_completion(text: str) -> str:
    """Return one canonical fenced program for both prediction and gold.

    LightEval's code scorers extract the body between the final two fences.
    The adapter therefore removes language labels and always writes the same
    fence shape, so a plain reference program and a fenced model program are
    represented identically without changing the official code execution
    scorer.
    """

    value = answer_region(text).strip()
    fences = list(re.finditer(r"(?m)^\s*```[^\n`]*\s*$", value))
    if len(fences) >= 2:
        body = value[fences[-2].end() : fences[-1].start()].strip("\n")
    elif len(fences) == 1:
        fence = fences[0]
        suffix = value[fence.end() :]
        if suffix.strip():
            body = suffix.strip("\n")
        else:
            body = value[: fence.start()].strip("\n")
    else:
        body = value.strip("\n")
    return f"```\n{body}\n```" if body else ""


def adapt_answer(
    text: str,
    *,
    domain: str | None,
    request_format: str | None,
    prompt: str = "",
    stops: Iterable[str] = (),
) -> str:
    """Map one raw RWKV completion to the canonical scoring text."""

    value = truncate_rwkv_completion(text, stops)
    domain_name = str(domain or "").strip().lower()
    format_name = str(request_format or "").strip().lower()
    if format_name in _CHOICE_FORMATS:
        return extract_choice_answer_v2(value, prompt=prompt)
    if format_name in _MATH_FORMATS or domain_name == "math":
        return extract_math_answer(value)
    if format_name in _CODE_FORMATS or domain_name == "coding":
        return extract_code_completion(value)
    # Instruction Following is intentionally NoCoT-only in the suite.  It is
    # not an answer-extraction task: the complete response is the object that
    # the native constraint scorer checks.
    return answer_region(value)
