"""Small, RWKV-oriented answer adapters used before LightEval scoring.

The model is prompted in the RWKV chat format, while a number of LightEval
metrics expect the answer to already be in their canonical form.  Keep that
boundary explicit: raw completions remain untouched in ``ModelResponse.text``
and this module only produces ``text_post_processed`` for scoring.
"""

from __future__ import annotations

import re
from typing import Iterable

try:
    # This is the checked-in LightEval source used by the project, not an
    # external runtime dependency. Reuse its established LaTeX equivalence
    # rules after extracting the final answer.
    from lighteval.metrics.normalizations import math_normalizer as _official_math_normalizer
except ImportError:  # pragma: no cover - standalone adapter tests
    _official_math_normalizer = None


_USER_TURN = "\nUser:"
_EOD = "\x00"
_CODE_FORMATS = {
    "code",
    "code_completion",
    "diff_patch",
    "generic_code",
    "python_function",
    "python_program",
    "python_snippet",
}
_CHOICE_FORMATS = {"choice", "multiple_choice", "multichoice", "mmlu"}
_MATH_FORMATS = {"math", "math_boxed", "math_free_response", "math_open_qa"}


def truncate_rwkv_completion(text: str, stops: Iterable[str] = ()) -> str:
    """Apply the text-level RWKV turn/EOD guards.

    The endpoint already applies its JSON ``stop`` list.  Repeating the
    guards here is intentional: score-only runs reconstruct responses from
    the database and must use the same boundary even when an old row was
    generated by a different endpoint implementation.
    """

    value = str(text or "")
    positions = [position for position in (value.find(_USER_TURN), value.find(_EOD)) if position >= 0]
    for stop in stops:
        marker = str(stop or "")
        if marker and marker not in {_USER_TURN, _EOD}:
            position = value.find(marker)
            if position >= 0:
                positions.append(position)
    return value[: min(positions)] if positions else value


def answer_region(text: str) -> str:
    """Remove a completed think block without guessing inside an open one."""

    value = str(text or "")
    closing = value.lower().rfind("</think>")
    if closing >= 0:
        return value[closing + len("</think>") :].lstrip()
    return value.strip()


def _choice_letters(prompt: str) -> set[str]:
    value = str(prompt or "")
    # Statements such as ``I.``/``II.`` often appear at the beginning of a
    # multiple-choice question. Parse labels only from the answer choices
    # section so those Roman-numeral statements cannot reject A/B/C/D.
    marker = re.search(r"answer\s+choices?\s*[:：]", value, re.IGNORECASE)
    choices_text = value[marker.end() :] if marker else value
    matches = re.findall(
        r"(?:\(([A-Z])\)|\[([A-Z])\]|^\s*([A-Z])\s*[.):：])",
        choices_text,
        re.IGNORECASE | re.MULTILINE,
    )
    labels = {
        group.upper()
        for match in matches
        for group in match
        if group
    }
    return labels or set("ABCD")


def extract_choice_answer(text: str, *, prompt: str = "") -> str:
    """Extract one final option and return the official ``" A"`` form.

    The order mirrors the RWKV knowledge evaluator: a direct standalone
    letter wins, then an explicit answer cue, then a final option-shaped line.
    We deliberately do not scan arbitrary capital letters from the reasoning.
    """

    value = answer_region(text)
    valid = _choice_letters(prompt)
    direct = re.fullmatch(r"\s*[\[\(]?([A-Z])[\]\)]?\s*[.!]?\s*", value, re.IGNORECASE)
    if direct and direct.group(1).upper() in valid:
        return f" {direct.group(1).upper()}"

    cues = re.compile(
        r"(?:final\s+answer|correct\s+answer|answer|答案|正确选项|选项)"
        r"\s*(?:is|为|是)?\s*[:：]?\s*[\[\(]?([A-Z])[\]\)]?\b",
        re.IGNORECASE,
    )
    for match in reversed(list(cues.finditer(value))):
        letter = match.group(1).upper()
        if letter in valid:
            return f" {letter}"

    line_pattern = re.compile(r"^\s*[\[\(]?([A-Z])[\]\)]?\s*[.):：-](?:\s|$)", re.IGNORECASE)
    for line in reversed([line for line in value.splitlines() if line.strip()]):
        match = line_pattern.match(line)
        if match and match.group(1).upper() in valid:
            return f" {match.group(1).upper()}"
    # Some native judge tasks use ``choice`` as their transport format but
    # their answer is a short textual verdict (for example ``Judgement: Yes``)
    # rather than A/B/C/D. Returning the final answer line here keeps that
    # task symmetric with the reference-side adapter instead of silently
    # turning a valid response into an empty answer.
    lines = [line.strip() for line in value.splitlines() if line.strip()]
    return lines[-1] if lines else ""


def _last_boxed(text: str) -> str | None:
    matches = list(re.finditer(r"\\(?:boxed|fbox)\s*\{", text, re.IGNORECASE))
    for match in reversed(matches):
        start = match.end()
        depth = 1
        for index in range(start, len(text)):
            if text[index] == "{" and (index == 0 or text[index - 1] != "\\"):
                depth += 1
            elif text[index] == "}" and (index == 0 or text[index - 1] != "\\"):
                depth -= 1
                if depth == 0:
                    return text[start:index].strip()
    return None


def _normalize_math_value(value: str) -> str:
    """Return one delimiter-free value for both prediction and gold text."""

    normalized = str(value or "").strip().strip("` ")
    wrappers = (("\\(", "\\)"), ("\\[", "\\]"))
    changed = True
    while changed and normalized:
        changed = False
        for left, right in wrappers:
            if normalized.startswith(left) and normalized.endswith(right):
                normalized = normalized[len(left) : -len(right)].strip()
                changed = True
        if len(normalized) >= 2 and normalized[0] == normalized[-1] == "$":
            normalized = normalized[1:-1].strip()
            changed = True
    normalized = normalized.replace("\\left", "").replace("\\right", "")
    normalized = normalized.replace("\\!", "")
    normalized = normalized.replace("\\dfrac", "\\frac").replace("\\tfrac", "\\frac")
    normalized = re.sub(r"\s+", "", normalized)
    return normalized.rstrip(".。")


def _format_math_value(value: str) -> str:
    normalized = _normalize_math_value(value)
    if normalized and _official_math_normalizer is not None:
        # LightEval's normalizer expects a complete solution containing a
        # boxed answer. Re-wrap our already extracted value to reuse its
        # fraction/spacing equivalence rules.
        normalized = _official_math_normalizer(f"\\boxed{{{normalized}}}") or normalized
    return f"${normalized}$" if normalized else ""


def normalize_math_answer(value: str) -> str:
    """Canonicalize one mathematical answer, whether it is gold or model text.

    This is deliberately separate from extraction: callers can pass either a
    raw completion or a dataset answer through the same function. In
    particular ``$4000$``, ``\\boxed{4000}``, and ``4000`` all become the same
    LaTeX value.
    """

    raw = str(value or "")
    boxed = _last_boxed(raw)
    if boxed is not None:
        raw = boxed
    return _format_math_value(raw)


def extract_math_answer(text: str) -> str:
    """Extract one canonical mathematical value from either side of a match.

    Gold rows and model continuations are deliberately sent through this same
    function. The scorer should compare ``36`` with ``36`` rather than rely on
    whether one side happened to contain ``$`` or ``\\boxed{...}``.
    """

    raw_value = str(text or "")
    # Math answers may be emitted inside the think block.  Search the complete
    # response first and choose the last *complete* boxed expression; the
    # parser skips a later, truncated ``\boxed{`` and can still use an earlier
    # complete answer.
    boxed = _last_boxed(raw_value)
    if boxed is not None:
        return normalize_math_answer(boxed)

    if re.search(r"\\(?:boxed|fbox)\s*\{", raw_value, re.IGNORECASE):
        return ""

    value = answer_region(raw_value)

    answer_cue = re.compile(
        r"(?:final\s+answer|answer|therefore|答案|结果|所以)\s*(?:is|为|是)?\s*[:：]?\s*(.+)",
        re.IGNORECASE,
    )
    matches = list(answer_cue.finditer(value))
    if matches:
        candidate = matches[-1].group(1).strip()
    else:
        lines = [line.strip() for line in value.splitlines() if line.strip()]
        candidate = lines[-1] if lines else ""
    return normalize_math_answer(candidate)


def extract_code_completion(text: str) -> str:
    """Return one canonical fenced program for both prediction and gold.

    LightEval's code scorers extract the body between the final two fences.
    The adapter therefore removes language labels and always writes the same
    fence shape, so a plain reference program and a fenced model program are
    represented identically without changing the official code execution
    scorer.
    """

    value = answer_region(text).strip()
    fences = list(re.finditer(r"(?m)^\s*```[^\n`]*\s*$", value))
    if len(fences) >= 2:
        body = value[fences[-2].end() : fences[-1].start()].strip("\n")
    elif len(fences) == 1:
        fence = fences[0]
        suffix = value[fence.end() :]
        if suffix.strip():
            body = suffix.strip("\n")
        else:
            body = value[: fence.start()].strip("\n")
    else:
        body = value.strip("\n")
    return f"```\n{body}\n```" if body else ""


def adapt_answer(
    text: str,
    *,
    domain: str | None,
    request_format: str | None,
    prompt: str = "",
    stops: Iterable[str] = (),
) -> str:
    """Map one raw RWKV completion to the canonical scoring text."""

    value = truncate_rwkv_completion(text, stops)
    domain_name = str(domain or "").strip().lower()
    format_name = str(request_format or "").strip().lower()
    if format_name in _CHOICE_FORMATS:
        return extract_choice_answer(value, prompt=prompt)
    if format_name in _MATH_FORMATS or domain_name == "math":
        return extract_math_answer(value)
    if format_name in _CODE_FORMATS or domain_name == "coding":
        return extract_code_completion(value)
    # Instruction Following is intentionally NoCoT-only in the suite.  It is
    # not an answer-extraction task: the complete response is the object that
    # the native constraint scorer checks.
    return answer_region(value)
